# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cauldrongo < Formula
  desc "Fetch Cauldron metrics"
  homepage ""
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.1.0/cauldrongo_Darwin_x86_64.tar.gz"
      sha256 "4c45d2f994fcc115ace2d6faa2e2f6cdeee9b00f112f941e17853e602b06632d"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.1.0/cauldrongo_Darwin_arm64.tar.gz"
      sha256 "7c847f7dadb82bb454fad8470dc923b5956cad2f9cb3616d05e51aae1eae4503"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.1.0/cauldrongo_Linux_x86_64.tar.gz"
      sha256 "8bf22d48720f44b574915e3c184f4c0e4450762a913fe21374d8fcfd6ca373c8"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.1.0/cauldrongo_Linux_armv7.tar.gz"
      sha256 "6fb61c36071c72ca072fb436f1c5727aee1eb65a4b770a8441442c73f6540c08"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.1.0/cauldrongo_Linux_arm64.tar.gz"
      sha256 "39f877008463c7b21b8787376ed67e3713d766a097da509e483a9106230ee7be"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  test do
    system "#{bin}/cauldrongo -v"
  end
end
