# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cauldrongo < Formula
  desc "Fetch Cauldron metrics"
  homepage ""
  version "0.0.1"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.1/cauldrongo_Darwin_x86_64.tar.gz"
      sha256 "f8c9dc8b4fad7d1deb9d5e2a83b427ba4dd3dfc936e8bccda9e620b79f34baae"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.1/cauldrongo_Darwin_arm64.tar.gz"
      sha256 "9f8f2c63e38da0274e8fdf61128bfb4b982afbb21b477e00f86de05a9290b1df"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.1/cauldrongo_Linux_x86_64.tar.gz"
      sha256 "41dd749c3123becea031f7825dcee67e37fed62462d50000611b6df4735b2522"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.1/cauldrongo_Linux_armv7.tar.gz"
      sha256 "299f92b6a62bdecbfe2795c1124d04f5f21126971673c8d2e2e482e4c00f114a"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.1/cauldrongo_Linux_arm64.tar.gz"
      sha256 "b82b999c07a9ae15e6a17300bb2786603663ca18114c100c8e5b1ece05fb91a0"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  test do
    system "#{bin}/cauldrongo -v"
  end
end
