# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cauldrongo < Formula
  desc "Fetch Cauldron metrics"
  homepage ""
  version "0.0.1-next"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.0/cauldrongo_Darwin_x86_64.tar.gz"
      sha256 "6d654559250dee7435352dd0c9c54bc23498f91d52acbeee3077d4f66ca58ea5"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.0/cauldrongo_Darwin_arm64.tar.gz"
      sha256 "6b943ffa8a43ea55e0cd86a2449111a159a8a0e54b47f5d5be68c7141a6e1e3f"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.0/cauldrongo_Linux_x86_64.tar.gz"
      sha256 "cc3771d4a63d3943fa091bedfd1d5e22019c121ed0bb44f00a1139006910b4bd"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.0/cauldrongo_Linux_armv7.tar.gz"
      sha256 "53b39afdc861f41ffc6eed0ff0af869d386502393775ec6195b8e524c509c74b"

      def install
        bin.install "cauldrongo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/cauldrongo/releases/download/v0.0.0/cauldrongo_Linux_arm64.tar.gz"
      sha256 "cb52e8c1859d686af404fbb60e5fe8f32d6976e656e457b5fde181bf3edacd4e"

      def install
        bin.install "cauldrongo"
      end
    end
  end

  test do
    system "#{bin}/cauldrongo -v"
  end
end
